version: '3'
services:

  app:
    image: node:14-slim
    ports:
      - 3030:3030
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run start
  cors:
    image: node:14-slim
    ports:
      - 3031:3031
    volumes:
      - ./cors:/app
    working_dir: /app
    command: npm run start
